id: IACC5DCDC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T03:37:19+00:00'
last_modified: '2022-06-08T12:57:09.754915+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29296
  title: དབུ་མ་འཇུག་པའི་མཐའ་དཔྱོད་ལུང་རིགས་གཏེར་མཛོད་ཟབ་དོན་ཀུན་གསལ་སྐལ་བཟང་འཇུག་ངོགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E582:
      image_group_id: I1PD36353
      title: Volume 1 of dbu ma 'jug pa'i mtha' dpyod lung rigs gter mdzod zab don
        kun gsal skal bzang 'jug ngogs
      total_pages: 468
      order: 1
      base_file: E582.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
