id: P006957
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:32:50.803289
source_metadata:
  id: bdr:W29296
  title: དབུ་མ་འཇུག་པའི་མཐའ་དཔྱོད་ལུང་རིགས་གཏེར་མཛོད་ཟབ་དོན་ཀུན་གསལ་སྐལ་བཟང་འཇུག་ངོགས
  author: ''
  volumes:
    e02753ea7f194161b50f4f38bc460cf4:
      image_group_id: I1PD36353
      title: Volume 1 of dbu ma 'jug pa'i mtha' dpyod lung rigs gter mdzod zab don
        kun gsal skal bzang 'jug ngogs
      volume_number: 1
      total_pages: 468
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
