id: P006957
initial_creation_type: ocr
source_metadata:
  id: bdr:W29296
  title: དབུ་མ་འཇུག་པའི་མཐའ་དཔྱོད་ལུང་རིགས་གཏེར་མཛོད་ཟབ་དོན་ཀུན་གསལ་སྐལ་བཟང་འཇུག་ངོགས
  author: ''
  volumes:
    f7f85c9e0fea4941abcd51135a30d3dc:
      image_group_id: I1PD36353
      title: ''
      volume_number: 1
      total_pages: 468
ebook_metadata:
  title: དབུ་མ་འཇུག་པའི་མཐའ་དཔྱོད་ལུང་རིགས་གཏེར་མཛོད་ཟབ་དོན་ཀུན་གསལ་སྐལ་བཟང་འཇུག་ངོགས
  author: ''
  sku: P006957
  cover: cover.jpg
  layers:
  - pagination
